<?php

namespace TenantCloud\RentlerSDK\Fake;

use TenantCloud\RentlerSDK\ProfileShares\CreditReportDTO;
use TenantCloud\RentlerSDK\ProfileShares\CriminalReportDTO;
use TenantCloud\RentlerSDK\ProfileShares\EvictionReportDTO;
use TenantCloud\RentlerSDK\ProfileShares\PaginatedProfileSharesResponseDTO;
use TenantCloud\RentlerSDK\ProfileShares\ProfileShareDTO;
use TenantCloud\RentlerSDK\ProfileShares\ProfileSharesApi;
use TenantCloud\RentlerSDK\ProfileShares\SearchProfileSharesDTO;

class FakeProfileSharesApi implements ProfileSharesApi
{
	public const NOT_EXISTING_ID = 10000;

	public const PROFILE_SHARE_ITEM = [
		'tenantId'                => 0,
		'landlordId'              => 0,
		'propertyId'              => 0,
		'profileShareId'          => 0,
		'tenantProfileSnapshotId' => 'string',
		'tenantProfileSnapshot'   => [
			'firstName'        => 'string',
			'lastName'         => 'string',
			'phone'            => 'string',
			'email'            => 'string',
			'doesSmoke'        => true,
			'isMilitary'       => true,
			'hasConviction'    => true,
			'convictionText'   => 'string',
			'isCitizen'        => true,
			'citizenText'      => 'string',
			'hasFiledBankrupt' => true,
			'bankruptText'     => 'string',
			'hasRefusedRent'   => true,
			'refusedRentText'  => 'string',
			'hasEviction'      => true,
			'evictionText'     => 'string',
			'incomeSources'    => [
				[
					'source'        => 'string',
					'monthlyIncome' => 0,
					'incomeType'    => 'string',
				],
			],
			'vehicles' => [
				[
					'type'               => 'string',
					'make'               => 'string',
					'model'              => 'string',
					'year'               => 0,
					'color'              => 'string',
					'licensePlateNumber' => 'string',
					'licensePlateState'  => 'string',
				],
			],
			'employers' => [
				[
					'companyName' => 'string',
					'position'    => 'string',
					'isFullTime'  => true,
					'address'     => [
						'address1' => 'string',
						'address2' => 'string',
						'city'     => 'string',
						'state'    => 'string',
						'zip'      => 'string',
					],
					'yearsEmployed' => 0,
					'monthlyIncome' => 0,
					'isCurrent'     => true,
					'companyPhone'  => 'string',
					'startDateUtc'  => '2022-05-18T16:07:00.477Z',
					'endDateUtc'    => '2022-05-18T16:07:00.477Z',
				],
			],
			'dependents' => [
				[
					'firstName'    => 'string',
					'lastName'     => 'string',
					'age'          => 0,
					'relationship' => 'string',
				],
			],
			'rentals' => [
				[
					'address' => [
						'address1' => 'string',
						'address2' => 'string',
						'city'     => 'string',
						'state'    => 'string',
						'zip'      => 'string',
					],
					'type'          => 'string',
					'monthlyRent'   => 0,
					'tenancyLength' => 0,
					'isCurrent'     => true,
					'landlordName'  => 'string',
					'landlordPhone' => 'string',
					'landlordEmail' => 'string',
				],
			],
			'contacts' => [
				[
					'name'         => 'string',
					'relationship' => 'string',
					'phone'        => 'string',
					'email'        => 'string',
				],
			],
			'pets' => [
				[
					'type'       => 'string',
					'name'       => 'string',
					'breed'      => 'string',
					'coloration' => 'string',
					'age'        => 0,
					'weight'     => 0,
					'sex'        => 'string',
					'isNeutered' => true,
					'otherType'  => 'string',
				],
			],
			'id'          => 'string',
			'screeningId' => 0,
		],
		'createDateUtc' => '2022-05-18T16:07:00.477Z',
		'updateDateUtc' => '2022-05-18T16:07:00.477Z',
	];

	public const PROFILE_SHARE_CRIMINAL_ITEM = [
		'createdOn'         => '2022-05-18T16:13:49.582Z',
		'requestedConsumer' => [
			'firstName'          => 'string',
			'middleName'         => 'string',
			'lastName'           => 'string',
			'dateOfBirth'        => '2022-05-18T16:13:49.582Z',
			'generationalSuffix' => 'string',
			'address'            => [
				'addressLine1' => 'string',
				'addressLine2' => 'string',
				'addressLine3' => 'string',
				'addressLine4' => 'string',
				'locality'     => 'string',
				'region'       => 'string',
				'postalCode'   => 'string',
				'country'      => 'string',
			],
			'age' => 0,
		],
		'criminalIdentityCount'    => 0,
		'sexOffenderIdentityCount' => 0,
		'mostWantedIdentityCount'  => 0,
		'ofacIdentityCount'        => 0,
		'otherIdentityCount'       => 0,
		'identities'               => [
			[
				'stateKey'                     => 'string',
				'sourceState'                  => 'string',
				'productType'                  => 'string',
				'criminalIdNumber'             => 'string',
				'firstName'                    => 'string',
				'middleName'                   => 'string',
				'lastName'                     => 'string',
				'suffix'                       => 'string',
				'fullName'                     => 'string',
				'age'                          => 'string',
				'birthPlace'                   => 'string',
				'citizenship'                  => 'string',
				'driversLicenseExpirationYear' => 'string',
				'driversLicenseNumber'         => 'string',
				'driversLicenseState'          => 'string',
				'eye'                          => 'string',
				'hair'                         => 'string',
				'height'                       => 'string',
				'weight'                       => 'string',
				'race'                         => 'string',
				'sex'                          => 'string',
				'ethnicity'                    => 'string',
				'complexion'                   => 'string',
				'scarMarkTattoo'               => 'string',
				'bodyBuild'                    => 'string',
				'address1'                     => 'string',
				'address2'                     => 'string',
				'city'                         => 'string',
				'state'                        => 'string',
				'postalCode'                   => 'string',
				'county'                       => 'string',
				'title'                        => 'string',
				'remarks'                      => 'string',
				'dateTimeModified'             => '2022-05-18T16:13:49.582Z',
				'idNumbers'                    => [
					[
						'idNumberType' => 'string',
						'typeText'     => 'string',
					],
				],
				'caseProperty' => [
					'offenses' => [
						[
							'sequence'                  => 'string',
							'offenseDate'               => '2022-05-18T16:13:49.582Z',
							'numberOfCounts'            => 0,
							'chargeDate'                => '2022-05-18T16:13:49.582Z',
							'status'                    => 'string',
							'statusDate'                => '2022-05-18T16:13:49.582Z',
							'description'               => 'string',
							'statute'                   => 'string',
							'pleaDate'                  => '2022-05-18T16:13:49.582Z',
							'chargeModifier'            => 'string',
							'type'                      => 'string',
							'classProperty'             => 'string',
							'degree'                    => 'string',
							'level'                     => 'string',
							'offenseTypeDescription'    => 'string',
							'plea'                      => 'string',
							'dispositionDescription'    => 'string',
							'dispositionDate'           => '2022-05-18T16:13:49.583Z',
							'dispositionStatus'         => 'string',
							'dispositionStatusDate'     => '2022-05-18T16:13:49.583Z',
							'dispositionConvictionDate' => '2022-05-18T16:13:49.583Z',
							'dispositionCounty'         => 'string',
							'sentenceTerm'              => 'string',
							'paroleTerm'                => 'string',
							'arrestDate'                => '2022-05-18T16:13:49.583Z',
							'paroleDate'                => '2022-05-18T16:13:49.583Z',
							'admittedDate'              => '2022-05-18T16:13:49.583Z',
							'ncicCode'                  => 'string',
							'minSentenceTerm'           => 'string',
							'maxSentenceTerm'           => 'string',
							'probationTerm'             => 'string',
							'sentenceDate'              => '2022-05-18T16:13:49.583Z',
							'probationDate'             => '2022-05-18T16:13:49.583Z',
							'releaseDate'               => '2022-05-18T16:13:49.583Z',
							'fines'                     => 0,
							'courtCosts'                => 0,
							'offenseCounty'             => 'string',
						],
					],
					'caseNumber'        => 'string',
					'disposition'       => 'string',
					'dispositionDate'   => '2022-05-18T16:13:49.583Z',
					'title'             => 'string',
					'county'            => 'string',
					'filingAgency'      => 'string',
					'filingDate'        => '2022-05-18T16:13:49.583Z',
					'type'              => 'string',
					'completionDate'    => '2022-05-18T16:13:49.583Z',
					'jurisdiction'      => 'string',
					'statusBeginDate'   => '2022-05-18T16:13:49.583Z',
					'statusDate'        => '2022-05-18T16:13:49.583Z',
					'statusDescription' => 'string',
					'statusEndDate'     => '2022-05-18T16:13:49.583Z',
				],
				'offenses' => [
					[
						'sequence'                  => 'string',
						'offenseDate'               => '2022-05-18T16:13:49.583Z',
						'numberOfCounts'            => 0,
						'chargeDate'                => '2022-05-18T16:13:49.583Z',
						'status'                    => 'string',
						'statusDate'                => '2022-05-18T16:13:49.583Z',
						'description'               => 'string',
						'statute'                   => 'string',
						'pleaDate'                  => '2022-05-18T16:13:49.583Z',
						'chargeModifier'            => 'string',
						'type'                      => 'string',
						'classProperty'             => 'string',
						'degree'                    => 'string',
						'level'                     => 'string',
						'offenseTypeDescription'    => 'string',
						'plea'                      => 'string',
						'dispositionDescription'    => 'string',
						'dispositionDate'           => '2022-05-18T16:13:49.583Z',
						'dispositionStatus'         => 'string',
						'dispositionStatusDate'     => '2022-05-18T16:13:49.583Z',
						'dispositionConvictionDate' => '2022-05-18T16:13:49.583Z',
						'dispositionCounty'         => 'string',
						'sentenceTerm'              => 'string',
						'paroleTerm'                => 'string',
						'arrestDate'                => '2022-05-18T16:13:49.583Z',
						'paroleDate'                => '2022-05-18T16:13:49.583Z',
						'admittedDate'              => '2022-05-18T16:13:49.583Z',
						'ncicCode'                  => 'string',
						'minSentenceTerm'           => 'string',
						'maxSentenceTerm'           => 'string',
						'probationTerm'             => 'string',
						'sentenceDate'              => '2022-05-18T16:13:49.583Z',
						'probationDate'             => '2022-05-18T16:13:49.583Z',
						'releaseDate'               => '2022-05-18T16:13:49.583Z',
						'fines'                     => 0,
						'courtCosts'                => 0,
						'offenseCounty'             => 'string',
					],
				],
				'aliases' => [
					[
						'firstName'  => 'string',
						'middleName' => 'string',
						'lastName'   => 'string',
					],
				],
				'imageUrl'         => 'string',
				'incidentCount'    => 0,
				'arrestCount'      => 0,
				'bookingCount'     => 0,
				'courtActionCount' => 0,
				'sentencingCount'  => 0,
				'supervisionCount' => 0,
			],
		],
		'disclaimers' => [
			[
				'key'   => 'string',
				'value' => 'string',
			],
		],
		'permissiblePurpose' => 'string',
		'screeningStatus'    => 'IdentityVerificationPending',
	];
	public const PROFILE_SHARE_CREDIT_ITEM = [
		'version'             => 'string',
		'document'            => 0,
		'componentIdentifier' => 'string',
		'bureau'              => 'string',
		'consumerId'          => 'string',
		'applicants'          => [
			[
				'status' => [
					'reportDate'   => '2022-05-18T16:11:29.150Z',
					'recordFound'  => 0,
					'frozenFile'   => true,
					'thinFile'     => true,
					'bureauStatus' => [
						'code' => [
							[
								'codeDescription' => 'string',
								'codeType'        => 'string',
								'description'     => 'string',
								'key'             => 'string',
							],
						],
					],
					'addressDiscrepancyIndicator' => 'string',
					'bureauErrorMessage'          => 'string',
				],
				'firstName'          => 'string',
				'middleName'         => 'string',
				'lastName'           => 'string',
				'suffix'             => 'string',
				'birthDate'          => '2022-05-18T16:11:29.151Z',
				'formattedBirthDate' => 'string',
				'ssn'                => 'string',
				'ssnMessage'         => 'string',
				'addresses'          => [
					[
						'streetAddress'    => 'string',
						'city'             => 'string',
						'state'            => 'string',
						'postalCode'       => 'string',
						'dateReported'     => '2022-05-18T16:11:29.151Z',
						'sourceIndicator'  => 'string',
						'addressQualifier' => 'string',
						'status'           => 'string',
					],
				],
				'publicRecords' => [
					[
						'publicRecordType'        => 'string',
						'recordCode'              => 'string',
						'statusCode'              => 'string',
						'memberCode'              => 'string',
						'narativeCode1'           => 'string',
						'narativeCode2'           => 'string',
						'dispositionCode'         => 'string',
						'industryCode'            => 'string',
						'dateSettled'             => '2022-05-18T16:11:29.151Z',
						'dateReported'            => '2022-05-18T16:11:29.151Z',
						'dateVerified'            => '2022-05-18T16:11:29.151Z',
						'amount'                  => 0,
						'assetAmount'             => 0,
						'accountDesignator'       => 'string',
						'referenceNumber'         => 'string',
						'legalDesignator'         => 'string',
						'plaintiff'               => 'string',
						'courtCode'               => 'string',
						'courtType'               => 'string',
						'courtLocationCity'       => 'string',
						'courtLocationState'      => 'string',
						'dateFiled'               => '2022-05-18T16:11:29.151Z',
						'dateFiledOriginal'       => '2022-05-18T16:11:29.151Z',
						'liabilitesAmount'        => 0,
						'typeOfBankruptcy'        => 'string',
						'intendedDispositionCode' => 'string',
					],
				],
				'tradelines' => [
					[
						'subscriberId'            => 'string',
						'subscriberName'          => 'string',
						'soldTo'                  => 'string',
						'narrativeCode1'          => 'string',
						'narrativeCode2'          => 'string',
						'narrativeCode3'          => 'string',
						'narrativeCode4'          => 'string',
						'dateReported'            => '2022-05-18T16:11:29.151Z',
						'terms'                   => 'string',
						'termsAmountOfPayment'    => 0,
						'balanceDate'             => '2022-05-18T16:11:29.151Z',
						'amount1'                 => 0,
						'amount1Qualifier'        => 'string',
						'amount2'                 => 0,
						'amount2Qualifier'        => 'string',
						'accountType'             => 'string',
						'accountNumber'           => 'string',
						'industryCode'            => 'string',
						'accountDesignator'       => 'string',
						'dateVerified'            => '2022-05-18T16:11:29.151Z',
						'dateOpened'              => '2022-05-18T16:11:29.151Z',
						'dateClosedIndicator'     => 'string',
						'dateClosed'              => '2022-05-18T16:11:29.151Z',
						'datePaidOut'             => '2022-05-18T16:11:29.151Z',
						'verificationIndicator'   => 'string',
						'currentMOP'              => 'string',
						'maximumDelinqDate'       => '2022-05-18T16:11:29.151Z',
						'highCredit'              => 0,
						'creditLimit'             => 0,
						'termsFrequencyOfPayment' => 'string',
						'loanType'                => 'string',
						'amountPastDue'           => 0,
						'previous1Date'           => '2022-05-18T16:11:29.151Z',
						'previous2Date'           => '2022-05-18T16:11:29.151Z',
						'previous3Date'           => '2022-05-18T16:11:29.151Z',
						'balanceAmount'           => 0,
						'paymentPattern'          => 'string',
						'paymentPatternStartDate' => '2022-05-18T16:11:29.151Z',
						'payments'                => [
							[
								'daysLate' => 0,
								'year'     => 0,
								'month'    => 0,
							],
						],
						'times30DaysLate'  => 0,
						'times60DaysLate'  => 0,
						'times90DaysLate'  => 0,
						'remarksCode'      => 'string',
						'originalCreditor' => 'string',
						'notes'            => 'string',
					],
				],
				'reportRetrievedOn' => '2022-05-18T16:11:29.151Z',
				'employments'       => [
					[
						'employerName'  => 'string',
						'city'          => 'string',
						'dateEmployed'  => '2022-05-18T16:11:29.151Z',
						'dateVerified'  => '2022-05-18T16:11:29.151Z',
						'postalCode'    => 'string',
						'state'         => 'string',
						'streetAddress' => 'string',
					],
				],
				'collections' => [
					[
						'accountDesignator'     => 'string',
						'accountNumber'         => 'string',
						'accountType'           => 'string',
						'collectionAgencyName'  => 'string',
						'creditorsName'         => 'string',
						'currentBalance'        => 0,
						'currentMOP'            => 'string',
						'customerNumber'        => 'string',
						'dateClosed'            => '2022-05-18T16:11:29.151Z',
						'dateClosedIndicator'   => 'string',
						'dateOpened'            => '2022-05-18T16:11:29.152Z',
						'datePaidOut'           => '2022-05-18T16:11:29.152Z',
						'dateReported'          => '2022-05-18T16:11:29.152Z',
						'dateVerified'          => '2022-05-18T16:11:29.152Z',
						'highCredit'            => 0,
						'industryCode'          => 'string',
						'loanType'              => 'string',
						'narrativeCode1'        => 'string',
						'narrativeCode2'        => 'string',
						'pastDue'               => 0,
						'remarksCode'           => 'string',
						'verificationIndicator' => 'string',
						'collectionComments'    => 'string',
					],
				],
				'collectionsCurrentBalanceTotal' => 0,
				'inquirySubscriber'              => [
					[
						'industryCode'   => 'string',
						'inquiryDate'    => '2022-05-18T16:11:29.152Z',
						'subscriberId'   => 'string',
						'subscriberName' => 'string',
						'type'           => 'string',
					],
				],
				'profileSummary' => [
					'closedWithBal' => [
						'balance'            => 0,
						'count'              => 0,
						'creditLimit'        => 0,
						'highCredit'         => 0,
						'monthlyPayment'     => 0,
						'percentCreditAvail' => 0,
					],
					'derogItems' => [
						'collectionCount'       => 0,
						'histNegTradelineCount' => 0,
						'negTradelineCount'     => 0,
						'occuranceHistCount'    => 0,
						'publicRecordCount'     => 0,
					],
					'installBalance' => 0,
					'installment'    => [
						'balance'            => 0,
						'count'              => 0,
						'creditLimit'        => 0,
						'highCredit'         => 0,
						'monthlyPayment'     => 0,
						'percentCreditAvail' => 0,
					],
					'monthlyPayment' => 0,
					'mortgage'       => [
						'balance'            => 0,
						'count'              => 0,
						'creditLimit'        => 0,
						'highCredit'         => 0,
						'monthlyPayment'     => 0,
						'percentCreditAvail' => 0,
					],
					'numberOfInquiries' => 0,
					'open'              => [
						'balance'            => 0,
						'count'              => 0,
						'creditLimit'        => 0,
						'highCredit'         => 0,
						'monthlyPayment'     => 0,
						'percentCreditAvail' => 0,
					],
					'pastDueAmount' => 0,
					'pastDueItems'  => [
						'closedWithBalPastDue' => 0,
						'installmentPastDue'   => 0,
						'mortgagePastDue'      => 0,
						'openPastDue'          => 0,
						'revolvingPastDue'     => 0,
						'totalPastDue'         => 0,
					],
					'publicRecordCount'   => 0,
					'realEstateBalance'   => 0,
					'realEstatePayment'   => 0,
					'revolveAvailPercent' => 0,
					'revolveBalance'      => 0,
					'revolving'           => [
						'balance'            => 0,
						'count'              => 0,
						'creditLimit'        => 0,
						'highCredit'         => 0,
						'monthlyPayment'     => 0,
						'percentCreditAvail' => 0,
					],
					'total' => [
						'balance'            => 0,
						'count'              => 0,
						'creditLimit'        => 0,
						'highCredit'         => 0,
						'monthlyPayment'     => 0,
						'percentCreditAvail' => 0,
					],
				],
				'scoreModel' => [
					'code'  => 'string',
					'score' => [
						'scoreCard'                  => 'string',
						'results'                    => 'string',
						'derogatoryAlert'            => true,
						'fileInquiriesImpactedScore' => true,
						'noScoreReason'              => 'string',
						'factors'                    => [
							[
								'rank'        => 'string',
								'description' => 'string',
							],
						],
					],
					'scoreName' => 'string',
				],
				'fraudIndicators' => [
					[
						'indicator' => 'string',
					],
				],
				'incomeEstimate' => 0,
				'fileSummary'    => [
					'fileHitIndicator'           => 0,
					'ssnMatchIndicator'          => 0,
					'fileMatchIndicator'         => 0,
					'consumerStatementIndicator' => true,
					'market'                     => 'string',
					'subMarket'                  => 'string',
					'creditDataStatus'           => [
						'suppressed'          => true,
						'suppressedSpecified' => true,
						'doNotPromote'        => [
							'indicator'        => true,
							'dateOfExpiration' => '2022-05-18T16:11:29.152Z',
						],
						'freeze' => [
							'indicator'     => true,
							'typeSpecified' => true,
						],
						'minor'             => true,
						'minorSpecified'    => true,
						'disputed'          => true,
						'disputedSpecified' => true,
					],
					'inFileSinceDate' => '2022-05-18T16:11:29.152Z',
				],
				'fileNumber' => 'string',
			],
		],
		'entityID'           => '3fa85f64-5717-4562-b3fc-2c963f66afa6',
		'searchStatus'       => 0,
		'transactionControl' => [
			'userRefNumber' => 'string',
			'subscriber'    => [
				'industryCode'                => 'string',
				'memberCode'                  => 'string',
				'inquirySubscriberPrefixCode' => 'string',
				'password'                    => 'string',
				'name'                        => 'string',
			],
			'options' => [
				'processingEnvironmentSpecified'   => true,
				'countrySpecified'                 => true,
				'languageSpecified'                => true,
				'contractualRelationshipSpecified' => true,
				'pointOfSaleIndicatorSpecified'    => true,
			],
			'customerLogin'        => 'string',
			'clientVendorSoftware' => 'string',
			'tracking'             => [
				'id'                            => 'string',
				'transactionTimeStamp'          => '2022-05-18T16:11:29.157Z',
				'transactionTimeStampSpecified' => true,
			],
		],
		'requestedConsumer' => [
			'firstName'          => 'string',
			'middleName'         => 'string',
			'lastName'           => 'string',
			'dateOfBirth'        => '2022-05-18T16:11:29.157Z',
			'generationalSuffix' => 'string',
			'address'            => [
				'addressLine1' => 'string',
				'addressLine2' => 'string',
				'addressLine3' => 'string',
				'addressLine4' => 'string',
				'locality'     => 'string',
				'region'       => 'string',
				'postalCode'   => 'string',
				'country'      => 'string',
			],
			'nationalIdentificationNumber' => 'string',
		],
		'permissiblePurpose' => 'string',
		'screeningStatus'    => 'IdentityVerificationPending',
	];
	public const PROFILE_SHARE_EVICTION_ITEM = [
		'createdOn'         => '2022-05-18T16:14:17.882Z',
		'requestedConsumer' => [
			'firstName'          => 'string',
			'middleName'         => 'string',
			'lastName'           => 'string',
			'dateOfBirth'        => '2022-05-18T16:14:17.882Z',
			'generationalSuffix' => 'string',
			'address'            => [
				'addressLine1' => 'string',
				'addressLine2' => 'string',
				'addressLine3' => 'string',
				'addressLine4' => 'string',
				'locality'     => 'string',
				'region'       => 'string',
				'postalCode'   => 'string',
				'country'      => 'string',
			],
			'age' => 0,
		],
		'records' => [
			[
				'firstName'          => 'string',
				'middleName'         => 'string',
				'lastName'           => 'string',
				'suffix'             => 'string',
				'address1'           => 'string',
				'address2'           => 'string',
				'city'               => 'string',
				'state'              => 'string',
				'postalCode'         => 'string',
				'stateKey'           => 'string',
				'datasetDescription' => 'string',
				'sourceState'        => 'string',
				'county'             => 'string',
				'recordId'           => 'string',
				'fileNumber'         => 'string',
				'filingDate'         => '2022-05-18T16:14:17.882Z',
				'actionType'         => 'string',
				'filingType'         => 'string',
				'releaseDate'        => 'string',
				'plaintiff'          => 'string',
				'amount'             => 'string',
				'comments'           => 'string',
				'events'             => [
					[
						'type'              => 'string',
						'eventID'           => 'string',
						'inDispute'         => 'string',
						'consumerStatement' => 'string',
						'court'             => [
							'name'    => 'string',
							'address' => [
								'addressLine1'              => 'string',
								'addressLine2'              => 'string',
								'addressLine3'              => 'string',
								'addressLine4'              => 'string',
								'locality'                  => 'string',
								'region'                    => 'string',
								'postalCode'                => 'string',
								'country'                   => 'string',
								'standardizedFlag'          => true,
								'addressClassificationCode' => 'string',
								'addressType'               => 'string',
								'addressTypeCode'           => 'string',
								'addressNumber'             => 'string',
								'preDirectionalCode'        => 'string',
								'postDirectionalCode'       => 'string',
								'streetName'                => 'string',
								'streetSuffix'              => 'string',
								'unitType'                  => 'string',
								'urbanizationName'          => 'string',
								'zipExtensionCode'          => 'string',
								'fipsCode'                  => 'string',
								'range'                     => 'string',
								'type'                      => 'string',
								'address1'                  => 'string',
								'address2'                  => 'string',
								'city'                      => 'string',
								'state'                     => 'string',
								'zipCode'                   => 'string',
								'locationType'              => 'string',
								'county'                    => 'string',
								'verificationDate'          => '2022-05-18T16:14:17.882Z',
								'reportDate'                => '2022-05-18T16:14:17.882Z',
								'buildingNumber'            => 'string',
							],
							'book' => 'string',
							'page' => 'string',
						],
						'originatingCourtDepartment'     => 'string',
						'filingType'                     => 'string',
						'filingDate'                     => '2022-05-18T16:14:17.882Z',
						'originalCourtBook'              => 'string',
						'originalCourtPage'              => 'string',
						'caseNumber'                     => 'string',
						'otherCaseNumber'                => 'string',
						'originalCaseNumber'             => 'string',
						'book'                           => 'string',
						'page'                           => 'string',
						'caseStatus'                     => 'string',
						'caseTitle'                      => 'string',
						'caseDescription'                => 'string',
						'caseType'                       => 'string',
						'response'                       => 'string',
						'responseFiledDate'              => '2022-05-18T16:14:17.882Z',
						'disposition'                    => 'string',
						'disposedDate'                   => '2022-05-18T16:14:17.882Z',
						'judgmentFor'                    => 'string',
						'judgmentType'                   => 'string',
						'judgmentDate'                   => '2022-05-18T16:14:17.882Z',
						'judgmentAmount'                 => 'string',
						'judgmentCondition'              => 'string',
						'dismissedType'                  => 'string',
						'dismissalDate'                  => '2022-05-18T16:14:17.882Z',
						'writType'                       => 'string',
						'writSatisfiedDate'              => '2022-05-18T16:14:17.882Z',
						'actionType'                     => 'string',
						'petitionDate'                   => '2022-05-18T16:14:17.882Z',
						'satisfactionDate'               => '2022-05-18T16:14:17.882Z',
						'vacatedDate'                    => '2022-05-18T16:14:17.882Z',
						'releaseDate'                    => 'string',
						'rentAmount'                     => 'string',
						'amountOrLiability'              => 'string',
						'assets'                         => 'string',
						'bankruptcyAssetDisclosureDate'  => '2022-05-18T16:14:17.882Z',
						'assetsAvailableForDistribution' => 'string',
						'restitutionOfPremises'          => 'string',
						'noticeDays'                     => 'string',
						'noticeType'                     => 'string',
						'comments'                       => 'string',
						'hearingResult'                  => 'string',
						'judgementSigned'                => 'string',
						'judgeIdentificationNumber'      => 'string',
						'parties'                        => [
							[
								'type'        => 'string',
								'phoneNumber' => 'string',
								'fullName'    => 'string',
								'firstName'   => 'string',
								'lastName'    => 'string',
								'middleName'  => 'string',
								'suffix'      => 'string',
								'gender'      => 'string',
							],
						],
					],
				],
			],
		],
		'disclaimers' => [
			'string',
		],
		'screeningStatus' => 'IdentityVerificationPending',
	];

	public function create(int $tenantId, int $landlordId, int $propertyId): ProfileShareDTO
	{
		$item = ProfileShareDTO::from(self::PROFILE_SHARE_ITEM);
		$item->setTenantId($tenantId);
		$item->setLandlordId($landlordId);
		$item->setPropertyId($propertyId);

		return $item;
	}

	public function list(SearchProfileSharesDTO $filtersDTO): PaginatedProfileSharesResponseDTO
	{
		$response = PaginatedProfileSharesResponseDTO::create();

		$response->setLimit(10)
			->setPage(1)
			->setTotalItems(2)
			->setTotalPages(1)
			->setItems([self::PROFILE_SHARE_ITEM]);

		return $response;
	}

	public function get(int $id): ProfileShareDTO
	{
		return ProfileShareDTO::from(self::PROFILE_SHARE_ITEM);
	}

	public function getCredit(int $id): CreditReportDTO
	{
		return CreditReportDTO::from(self::PROFILE_SHARE_CREDIT_ITEM);
	}

	public function getCriminal(int $id): CriminalReportDTO
	{
		return CriminalReportDTO::from(self::PROFILE_SHARE_CRIMINAL_ITEM);
	}

	public function getEviction(int $id): EvictionReportDTO
	{
		return EvictionReportDTO::from(self::PROFILE_SHARE_EVICTION_ITEM);
	}
}
